version: '3.8'
services:
  lmstockms:
    build: .
    container_name: lmstockms
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_APPLICATION_NAME=LMStockMS
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8090/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/stock_db
      - SPRING_DATASOURCE_USERNAME=stockuser
      - SPRING_DATASOURCE_PASSWORD=stock1234
    networks:
      - libmark-network

networks:
  libmark-network:
    external: true